service: wa-api-v1

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:accountId:table/LibraryTable
        - arn:aws:dynamodb:us-east-1:accountId:table/Cleaners

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/library/books
          method: GET
          cors: true
      - http:
          path: /api/library/books/{uid}
          method: GET
          cors: true
      - http:
          path: /api/library/books
          method: POST
          cors: true
      - http:
          path: /api/library/books/{uid}
          method: PUT
          cors: true
      - http:
          path: /api/library/books/{uid}
          method: DELETE
          cors: true
      - http:
          path: /api/wac/cleaners
          method: GET
          cors: true
      - http:
          path: /api/wac/cleaners/{uid}
          method: GET
          cors: true
      - http:
          path: /api/wac/cleaners
          method: POST
          cors: true
      - http:
          path: /api/wac/cleaners/{uid}
          method: PUT
          cors: true
      - http:
          path: /api/wac/cleaners/{uid}
          method: DELETE
          cors: true
      - http:
          path: /api/wac/new-cleaners
          method: GET
          cors: true

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LibraryTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    CleanersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Cleaners
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: wixMemberId
            AttributeType: S
          - AttributeName: name
            AttributeType: S
          - AttributeName: phoneNumber
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: rating
            AttributeType: N
          - AttributeName: ratingQ
            AttributeType: N
          - AttributeName: stripe
            AttributeType: BOOL
          - AttributeName: sterling
            AttributeType: BOOL
          - AttributeName: myTeams
            AttributeType: BOOL
          - AttributeName: myTeamsDefault
            AttributeType: BOOL
          - AttributeName: businessName
            AttributeType: S
          - AttributeName: phone
            AttributeType: S
          - AttributeName: address1
            AttributeType: S
          - AttributeName: address2
            AttributeType: S
          - AttributeName: city
            AttributeType: S
          - AttributeName: stateCode
            AttributeType: S
          - AttributeName: stateName
            AttributeType: S
          - AttributeName: postalCode
            AttributeType: S
          - AttributeName: lat
            AttributeType: N
          - AttributeName: lng
            AttributeType: N
          - AttributeName: status
            AttributeType: S
          - AttributeName: subscription
            AttributeType: S
          - AttributeName: enable
            AttributeType: BOOL
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: email
            KeyType: HASH

plugins:
  - serverless-offline
  - serverless-puresec-cli

custom:
  serverless-offline:
    noPrependStageInUrl: true