service: wa-api-v1

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: "20201221"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:890827230719:table/LibraryTable

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/library/books
          method: GET
      - http:
          path: /api/library/books/{uid}
          method: GET
      - http:
          path: /api/library/books
          method: POST
      - http:
          path: /api/library/books/{uid}
          method: PUT
      - http:
          path: /api/library/books/{uid}
          method: DELETE


resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LibraryTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-offline
  - serverless-puresec-cli

custom:
  serverless-offline:
    noPrependStageInUrl: true